name: generate-builds
on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-soh-otr:
    runs-on: ${{ (vars.LINUX_RUNNER && fromJSON(vars.LINUX_RUNNER)) || 'ubuntu-latest' }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.11
      with:
        key: ${{ runner.os }}-otr-ccache-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-otr-ccache-${{ github.ref }}
          ${{ runner.os }}-otr-ccache-
    - name: Install dependencies
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat .github/workflows/apt-deps.txt)
    - name: Cache build folders
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-otr-build-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-otr-build-${{ github.ref }}
          ${{ runner.os }}-otr-build-
        path: |
          build-cmake
          SDL2-2.28.5
    - name: Install latest SDL
      if: ${{ !vars.LINUX_RUNNER }}
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        if [ ! -d "SDL2-2.28.5" ]; then
          wget https://www.libsdl.org/release/SDL2-2.28.5.tar.gz
          tar -xzf SDL2-2.28.5.tar.gz
        fi
        cd SDL2-2.28.5
        ./configure --enable-hidapi-libusb
        make -j 10
        sudo make install
        sudo cp -av /usr/local/lib/libSDL* /lib/x86_64-linux-gnu/
    - name: Generate soh.otr
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cmake --no-warn-unused-cli -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE:STRING=Release
        cmake --build build-cmake --config Release --target GenerateSohOtr
    - uses: actions/upload-artifact@v4
      with:
        name: soh.otr
        path: soh.otr
        retention-days: 1
  build-switch:
    needs: generate-soh-otr
    runs-on: ${{ (vars.LINUX_RUNNER && fromJSON(vars.LINUX_RUNNER)) || 'ubuntu-latest' }}
    container:
      image: devkitpro/devkita64:20240120
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        sudo apt-get remove -y cmake
        wget https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-x86_64.sh -O /tmp/cmake.sh
        sudo sh /tmp/cmake.sh --prefix=/usr/local/ --exclude-subdir
        wget https://libzip.org/download/libzip-1.10.1.tar.gz
        tar -xzvf libzip-1.10.1.tar.gz
        cd libzip-1.10.1
        mkdir build
        cd build
        cmake -H.. -B. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
        make
        make install
        cd ../..
        wget https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
        tar -xzvf v3.11.3.tar.gz
        cd json-3.11.3
        mkdir build
        cd build
        cmake -H.. -B. -DJSON_BuildTests=OFF -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake
        make
        make install
        cd ../..

    - name: Fix dubious ownership error
      if: ${{ vars.LINUX_RUNNER }}
      run: git config --global --add safe.directory '*'
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.11
      with:
        key: ${{ runner.os }}-switch-ccache-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-switch-ccache-${{ github.ref }}
          ${{ runner.os }}-switch-ccache-
    - name: Build SoH
      run: |
        cmake -H. -Bbuild-switch -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
        cmake --build build-switch --target soh_nro -j3

        mv build-switch/soh/*.nro soh.nro
        mv README.md readme.txt
    - name: Download soh.otr
      uses: actions/download-artifact@v4
      with:
        name: soh.otr
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-switch
        path: |
          soh.nro
          soh.otr
          readme.txt
  build-windows:
    needs: generate-soh-otr
    runs-on: ${{ (vars.WINDOWS_RUNNER && fromJSON(vars.WINDOWS_RUNNER)) || 'windows-latest' }}
    steps:
    - name: Install dependencies
      if: ${{ !vars.WINDOWS_RUNNER }}
      run: |
        choco install ninja
        Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.11
      with:
        variant: sccache
        max-size: "1G"
        key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.ref }}
          ${{ runner.os }}-ccache-
    - name: Cache build folder
      uses: actions/cache@v4
      with:
        save-always: true
        key: ${{ runner.os }}-build-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-${{ github.ref }}
          ${{ runner.os }}-build-
        path: |
          build-windows
          vcpkg
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build SoH
      env: 
        VCPKG_ROOT: ${{github.workspace}}/vcpkg
      run: |
        set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
        cmake -S . -B build-windows -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DBUILD_REMOTE_CONTROL=1
        cmake --build build-windows --config Release --parallel 10

        mkdir soh-windows
        mv ./x64/Release/soh.exe ./soh-windows/soh.exe
        mkdir soh-windows/debug
        mkdir soh-windows/mods
        New-Item soh-windows/mods/custom_otr_files_go_here.txt -type file
        mv ./x64/Release/soh.pdb ./soh-windows/debug/soh.pdb
        mv ./README.md ./soh-windows/readme.txt
        mv ./build-windows/gamecontrollerdb.txt ./soh-windows/gamecontrollerdb.txt
        mv ./x64/Release/assets ./soh-windows
    - name: Download soh.otr
      uses: actions/download-artifact@v4
      with:
        name: soh.otr
        path: soh-windows
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: soh-windows
        path: soh-windows
